= xjot

XJot is a sparser representation of XML that requires less typing and squinting than regular XML.

== Motivation

@bigsmoke came up with XJot as he grew weary of using Asciidoc as basically an input format for DocBook. He kept fighting Asciidoctor and Pandoc to pass through all the information he wanted to be passed through from Asciidoc to DocBook, and all that because XML is all _too_ verbose.

Inventing yet another shitty, informal wiki-like, plain text syntax was not so appealing to @bigsmoke. Nor was finding an editor (or tweaking his `nvim` config) to make editing XML actually pleasant. So, he came up with yet another sparse representation for XML, as if there weren't already to many of these either.

== XJot syntax

=== XJot prolog

An XJot document starts with an XJot prolog

=== XJot elements

There are 3 kinds of elements

```
<section/
<p/ The content of this <tt/&lt;section&gt;/> element spans multiple paragraph.
<p/ Here, we put each paragraph on a separate line.
<p/ Let's put some extra vertical space below using the empty <tt/&lt;br&gt;/> element.
<br//
<p/ We can also use an empty element inline, like in <br/> this. Yes, this notation is exactly the same as in XML.
/section>
```

=== XJot element attributes

Attributes are prefixed by an `@` sign in XJot.

=== Indentation versus paths

Normally, indentation is use in XML documents to indicate hierarchical structure. In XJot, there is an alternative to indentation, which is particularly useful when authoring documents, even if only because SCM systems are normally not capable of seeing through indentation changes, meaning that a simple change in structure in an indented document will have a huge ripple effect in the diff size.

When you don't indent your XJot document, you are allowed to put as much of the path to an element that you're opening and closing in the start and end tags as is useful to you. Do note that the start and end tag must contain the same number of ancestral node names. The following is legal:

```
<chapter/
<chapter/section/
<chapter/section/title/ Legal example
/chapter/section>
/chapter>
```

The next example, however, is not well-formed:

```
<chapter/
<chapter/section/
<chapter/section/title/ Illegal example
/section>
/chapter>
```

Using paths also allows you to skip opening tags altogether, as in:

```
<chapter/
<chapter/info/title/ Chapter title element within info element
<chapter/section/
<chapter/section/info/title/ Again, we skip the opening tag for the info element
/chapter/section>
/chapter>
```

Elements that are implicitly opened in this way (like the `<info>` elements in this example), don't need to be closed explicitly, but they _may_.

=== XJot notation for XML processing instructions

In XML, a processing instruction (PI) consists of a `<?`, followed by the processing instruction _target_ (for instance, `php`), optionally followed by the processing instruction data, and closed by `?>`.

In XJot, PI notation follows the same structure as the notation for elements. If you need multiline PI data, you have to start the data on a new line, the PI closing tag has to be on a separate line as well, and, contrary to XML, the PI must be closed by repeating its name:

```
<?php/
echo "PI data";
/php?>
```

Inline PI without data:

```
Blabla bla bla <?counter/?> fdfdf
```

Inline PI with data:

```
Content before the PI <?counter/ one/?> and content after the PI.
```
